### ISSUE TITLE
Support for TLS servers

### ISSUE THREAD

**Issue by jonathannaguin** [txamqp/txamqp#13]
Hello,

I am trying to connect to a RabbitMQ configured as a TLS server, and I am getting an error similar to:

 <class 'txamqp.client.Closed'>: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'

Does this library support this type of setup?

Thanks!

**Comment by barryib** [comment]
@jonathannaguin did you get an answer to your question ? If yes can you share it please ?

If txamqp doesn't support AMQPS, maybe we should re-open this issue to track that feature request.
