### ISSUE TITLE
Encoding the content will limit the content type to only string

### ISSUE THREAD

**Issue by farirat** [txamqp/txamqp#4]
Starting from 0.8.0 the body content is now encoded before getting sent:

https://github.com/txamqp/txamqp/blob/871bb55466ef2e8280fb126b0e4ddb284888ee4f/src/txamqp/codec.py#L137

This will limit the content type only for *encodeable* strings, in my case i'm sending pickled objects (using protocol v2) and i get the following error:
> exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

This can be raised with such a simple content:
`txamqp.publish(exchange='anything', routing_key="any.route", content=Content(pickle.dumps('\x53', 2)))`

Am now forced to downgrade to 0.7.0 as the encoded were not performed anyway.

**Comment by esteve** [comment]
@terrycain given that you submitted this change and contribute to Jasmin as well, what do you think would be the best way to fix this? Thanks!

**Comment by terricain** [comment]
Hmm,  without looking at the code, I guess that its currently converting anything to binary, so a bytes object in python3. We could probably get away with not encoding if py2 as a python2 string encoded is still a string.

Will whip up something and let you know

**Comment by terricain** [comment]
@farirat you fancy trying out #6 to see if it solves your issue?

**Comment by farirat** [comment]
Gonna make a trial now, i've missed the updates here ..

**Comment by farirat** [comment]
@esteve @terrycain fixed some remaining encoding mess in #7.

**Comment by terricain** [comment]
@farirat Ahh, would that be why I saw some DLRs not being delivered with a `TypeError('url must be bytes, not unicode',)`?

**Comment by farirat** [comment]
@terrycain not sure if it's caused by this one ..
