### ISSUE TITLE
Error in txamqp.message with 0.8.0

### ISSUE THREAD

**Issue by fpoirotte** [txamqp/txamqp#5]
Hello,

While playing around with the new release of txAMQP (0.8.0) on travis-ci, I started getting fatal syntax errors when importing ``txamqp.message``

```
  (...redacted lines...)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/txamqp/message.py", line 23
    COMMON_FIELDS = {"content", "method", "fields"}
                              ^

SyntaxError: invalid syntax
```

How to reproduce:
* Install txAMQP 0.8.0
* Fire up a Python interpreter
* Try to load ``import txamqp.message``

Other information:
* Python version 2.6.9

Regards,
François

**Comment by freeekanayaka** [comment]
Unfortunately Python 2.6 is not supported anymore, since it has gone end-of-life. If you can't upgrade to Python 2.7 I'd suggest to either roll back to the previous txAMQP release or patch the offending line.

**Comment by fpoirotte** [comment]
Ok, thank you for taking the time to explain the situation.
